language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t zafatar/multi-container-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true zafatar/multi-container-client-test npm run test -- --coverage

after_success:
  - docker build -t zafatar/multi-container-client ./client
  - docker build -t zafatar/multi-container-nginx ./nginx
  - docker build -t zafatar/multi-container-server ./server
  - docker build -t zafatar/multi-container-worker ./worker
  # Login to the docker client
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push these images to the Dockerhub
  - docker push zafatar/multi-container-client
  - docker push zafatar/multi-container-nginx
  - docker push zafatar/multi-container-server
  - docker push zafatar/multi-container-worker